# Generated by Django 4.2.7 on 2024-01-04 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('michael', '0003_alter_profile_date_modified_meep'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
